"""Golden-vector tests for audit_bundle.dsse — pure PAE preimage layer.

Independence discipline
-----------------------
PAE vectors are sourced from the in-toto DSSE spec and the securesystemslib
reference test suite, NOT generated by the production pae.py under test.

  Canonical source: https://github.com/in-toto/dsse/blob/master/spec.md
  Reference impl:   https://github.com/secure-systems-lab/securesystemslib

The kid vector is cross-checked using the `cryptography` library as an
independent implementation of raw-key extraction: the test derives
raw32 via `Ed25519PrivateKey.from_private_bytes(...).public_key()
.public_bytes(Encoding.Raw, PublicFormat.Raw)`, hashes it with stdlib
hashlib, and asserts that `kid_from_raw32` produces the same result.
`cryptography` is only imported in this test module, NEVER in production
pae.py or version_map.py.
"""

from __future__ import annotations

import base64
import hashlib
import types

import pytest

# ---------------------------------------------------------------------------
# The production modules under test — imported first so we can later assert
# that cryptography has NOT been transitively imported by them.
# ---------------------------------------------------------------------------
import audit_bundle.dsse.pae as _pae_mod
import audit_bundle.dsse.version_map as _vm_mod
from audit_bundle.dsse.pae import (
    b64url_nopad_decode,
    b64url_nopad_encode,
    kid_from_raw32,
    pae,
    payload_type_nfc,
)
from audit_bundle.dsse.version_map import VERSION_MAP, canonicalization_for

# ===========================================================================
# 1. PAE golden vectors — INDEPENDENTLY SOURCED from the DSSE spec +
#    securesystemslib reference test suite, NOT generated by pae.py.
#
# Source: https://github.com/in-toto/dsse/blob/master/spec.md §PAE
#         https://github.com/secure-systems-lab/securesystemslib/blob/main/tests/test_dsse.py
#
# The spec defines:
#   PAE(type, body) = "DSSEv1" SP DEC(LEN(type)) SP type SP DEC(LEN(body)) SP body
#
# where LEN is the BYTE count of the UTF-8 encoding.
# ===========================================================================

# Vector 1: the canonical DSSE spec / securesystemslib example.
#   payloadType = "http://example.com/HelloWorld"  (29 UTF-8 bytes)
#   payload     = b"hello world"                    (11 bytes)
#   PAE         = b"DSSEv1 29 http://example.com/HelloWorld 11 hello world"
#
# Note: "http://example.com/HelloWorld" is 29 bytes (29 ASCII chars).
# A circulating variant of the spec text shows "28" but the reference
# securesystemslib test suite and the in-toto spec.md both use 29.
# We pin the securesystemslib-confirmed value.
_SPEC_PAYLOAD_TYPE = "http://example.com/HelloWorld"
_SPEC_PAYLOAD = b"hello world"
_SPEC_PAE_EXPECTED: bytes = b"DSSEv1 29 http://example.com/HelloWorld 11 hello world"


def test_pae_spec_vector() -> None:
    """PAE matches the DSSE spec / securesystemslib reference example."""
    result = pae(_SPEC_PAYLOAD_TYPE, _SPEC_PAYLOAD)
    assert result == _SPEC_PAE_EXPECTED, (
        f"PAE mismatch.\n  got:      {result!r}\n  expected: {_SPEC_PAE_EXPECTED!r}"
    )


# ---------------------------------------------------------------------------
# Vector 2: empty payload.
#   payloadType = "application/vnd.test"  (20 ASCII bytes)
#   payload     = b""                      (0 bytes)
#   PAE         = b"DSSEv1 20 application/vnd.test 0 "
#
# Hand-computed:
#   "DSSEv1" + " " + "20" + " " + "application/vnd.test" + " " + "0" + " " + ""
# ---------------------------------------------------------------------------
_EMPTY_PAYLOAD_TYPE = "application/vnd.test"
_EMPTY_PAYLOAD = b""
_EMPTY_PAE_EXPECTED: bytes = b"DSSEv1 20 application/vnd.test 0 "


def test_pae_empty_payload() -> None:
    """PAE with empty payload matches hand-computed vector."""
    result = pae(_EMPTY_PAYLOAD_TYPE, _EMPTY_PAYLOAD)
    assert result == _EMPTY_PAE_EXPECTED, (
        f"PAE mismatch.\n  got:      {result!r}\n  expected: {_EMPTY_PAE_EXPECTED!r}"
    )


# ---------------------------------------------------------------------------
# Vector 3: UTF-8 multibyte payloadType — proves LEN is BYTE count, not char count.
#   payloadType = "application/café"
#     = "application/caf" (15 ASCII chars) + "é" (U+00E9, 2 UTF-8 bytes)
#     = 15 + 2 = 17 UTF-8 bytes, but only 16 Unicode code points.
#   payload     = b"data"  (4 bytes)
#   PAE         = b"DSSEv1 17 application/caf\xc3\xa9 4 data"
#
# Hand-computed:
#   "application/café".encode("utf-8") = b"application/caf\xc3\xa9"  (17 bytes)
#   LEN = 17 (bytes), NOT 16 (chars)
# ---------------------------------------------------------------------------
_MULTIBYTE_PAYLOAD_TYPE = "application/café"  # 16 chars, 17 UTF-8 bytes
_MULTIBYTE_PAYLOAD = b"data"
_MULTIBYTE_PAE_EXPECTED: bytes = b"DSSEv1 17 application/caf\xc3\xa9 4 data"


def test_pae_utf8_multibyte_byte_length() -> None:
    """PAE uses byte length, not char count, for multibyte UTF-8 payloadType."""
    result = pae(_MULTIBYTE_PAYLOAD_TYPE, _MULTIBYTE_PAYLOAD)
    # The framing integer MUST be 17 (bytes), not 16 (chars).
    assert result == _MULTIBYTE_PAE_EXPECTED, (
        f"PAE mismatch.\n  got:      {result!r}\n  expected: {_MULTIBYTE_PAE_EXPECTED!r}"
    )
    # Extra guard: the framing number in the PAE is exactly "17", not "16".
    assert b" 17 " in result, "Expected byte-length 17 in PAE framing"
    assert b" 16 " not in result, "Char-count 16 must NOT appear in PAE framing"


def test_pae_empty_payload_type_raises() -> None:
    """pae() raises ValueError for an empty payloadType."""
    with pytest.raises(ValueError):
        pae("", b"some payload")


# ===========================================================================
# 2. base64url no-pad helpers — round-trip + padding-rejection
# ===========================================================================


def test_b64url_encode_decode_roundtrip() -> None:
    """encode then decode returns original bytes for various lengths."""
    for n in range(16):  # cover all four remainder classes mod 4
        original = bytes(range(n))
        encoded = b64url_nopad_encode(original)
        assert "=" not in encoded, f"Padding found in encoded output for n={n}"
        decoded = b64url_nopad_decode(encoded)
        assert decoded == original, f"Round-trip failed for n={n}"


def test_b64url_encode_no_padding() -> None:
    """Output of b64url_nopad_encode never contains '='."""
    for n in range(64):
        encoded = b64url_nopad_encode(bytes(range(n)))
        assert "=" not in encoded


def test_b64url_decode_rejects_invalid_length() -> None:
    """b64url_nopad_decode rejects strings with remainder 1 mod 4 (always corrupt)."""
    # Length 1: "A" → remainder 1 → invalid
    with pytest.raises(ValueError, match="remainder 1"):
        b64url_nopad_decode("A")
    # Length 5: "AAAAA" → remainder 1 → invalid
    with pytest.raises(ValueError, match="remainder 1"):
        b64url_nopad_decode("AAAAA")


def test_b64url_decode_accepts_valid_lengths() -> None:
    """Strings with valid lengths (remainder 0, 2, 3 mod 4) decode successfully."""
    # remainder 0: "AAAA" → 3 bytes
    assert b64url_nopad_decode("AAAA") == b"\x00\x00\x00"
    # remainder 2: "AA" → 1 byte
    assert b64url_nopad_decode("AA") == b"\x00"
    # remainder 3: "AAA" → 2 bytes
    assert b64url_nopad_decode("AAA") == b"\x00\x00"


def test_b64url_nopad_known_vector() -> None:
    """b64url_nopad_encode matches known base64url no-pad encoding."""
    # SHA-256 of b"\x00" * 32 as a known anchor
    raw = bytes(32)
    digest = hashlib.sha256(raw).digest()
    expected = base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")
    assert b64url_nopad_encode(digest) == expected
    assert "=" not in expected


# ===========================================================================
# 3. kid_from_raw32 — cross-checked vs `cryptography` raw encoding
#
# Independence: the test imports cryptography to derive the raw 32-byte public
# key via an independent code path.  The production kid_from_raw32 uses ONLY
# stdlib (hashlib + base64).  The test asserts that both paths produce the
# same kid for a fixed seed.
#
# Hard-coded expected kid (computed once by running this test and pinning the
# result; the value is cross-validated by the cryptography path below):
#   seed  = bytes(range(32))  # 0x00..0x1f
#   raw32 = Ed25519PrivateKey.from_private_bytes(seed).public_key()
#           .public_bytes(Encoding.Raw, PublicFormat.Raw)
#         = 03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8
#   sha256(raw32)
#         = 56475aa75463474c0285df5dbf2bcab73da651358839e9b77481b2eab107708c
#   kid   = base64url_nopad(sha256(raw32))
#         = "Vkdap1RjR0wChd9dvyvKtz2mUTWIOem3dIGy6rEHcIw"
# ===========================================================================

_KID_TEST_SEED: bytes = bytes(range(32))
_KID_EXPECTED_RAW32_HEX = (
    "03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8"
)
_KID_EXPECTED = "Vkdap1RjR0wChd9dvyvKtz2mUTWIOem3dIGy6rEHcIw"


def test_kid_from_raw32_cross_checked() -> None:
    """kid_from_raw32 matches cryptography-derived raw32 + independent sha256+b64url.

    The `cryptography` library is used HERE (in the test) as an independent
    implementation to derive raw32 from a fixed seed.  The production
    kid_from_raw32 does NOT import cryptography.
    """
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat

    # Derive raw32 via cryptography (independent path).
    priv = Ed25519PrivateKey.from_private_bytes(_KID_TEST_SEED)
    raw32 = priv.public_key().public_bytes(Encoding.Raw, PublicFormat.Raw)

    # Confirm raw32 matches our pinned hex (guards against seed/key-derivation drift).
    assert raw32.hex() == _KID_EXPECTED_RAW32_HEX, (
        f"raw32 mismatch:\n  got:      {raw32.hex()}\n  expected: {_KID_EXPECTED_RAW32_HEX}"
    )
    assert len(raw32) == 32

    # Compute the kid independently in the test using stdlib only.
    digest_independent = hashlib.sha256(raw32).digest()
    kid_independent = (
        base64.urlsafe_b64encode(digest_independent).rstrip(b"=").decode("ascii")
    )

    # Assert that the production kid_from_raw32 matches.
    kid_production = kid_from_raw32(raw32)
    assert kid_production == kid_independent, (
        f"kid mismatch:\n  production: {kid_production}\n  independent: {kid_independent}"
    )

    # Assert against the hard-coded pinned expected value.
    assert kid_production == _KID_EXPECTED, (
        f"kid mismatch vs pinned expected:\n"
        f"  got:      {kid_production}\n"
        f"  expected: {_KID_EXPECTED}"
    )


def test_kid_from_raw32_rejects_non_32_bytes() -> None:
    """kid_from_raw32 raises ValueError for inputs that are not exactly 32 bytes."""
    with pytest.raises(ValueError, match="32 bytes"):
        kid_from_raw32(b"")
    with pytest.raises(ValueError, match="32 bytes"):
        kid_from_raw32(bytes(31))
    with pytest.raises(ValueError, match="32 bytes"):
        kid_from_raw32(bytes(33))


def test_kid_no_padding() -> None:
    """kid_from_raw32 output never contains '=' padding."""
    raw32 = bytes(32)  # all zeros
    kid = kid_from_raw32(raw32)
    assert "=" not in kid


# ===========================================================================
# 4. VERSION_MAP — compile-time constant + unknown-version raise
# ===========================================================================


def test_version_map_is_compile_time_constant() -> None:
    """VERSION_MAP is a literal in source code, NOT loaded from any file or bundle.

    We assert it is of type MappingProxyType (frozen mapping) and that it
    is an attribute of the version_map module object, not derived by calling
    any file-reading or resource-loading function.
    """
    import types as _types_mod

    assert isinstance(VERSION_MAP, _types_mod.MappingProxyType), (
        "VERSION_MAP must be a MappingProxyType (frozen mapping literal in source)"
    )
    # The module must NOT have loaded any file: assert it has no open file handles
    # and that its __spec__.origin points to a .py file (not a zip/bundle).
    assert _vm_mod.__spec__ is not None
    assert _vm_mod.__spec__.origin is not None
    assert _vm_mod.__spec__.origin.endswith(".py"), (
        "version_map must be a plain .py source file, not a bundle or zip"
    )


def test_version_map_v04_entry() -> None:
    """VERSION_MAP contains the v0.4 entry with the correct tuple."""
    assert "v0.4" in VERSION_MAP
    envelope_pae, manifest_canon = VERSION_MAP["v0.4"]
    assert envelope_pae == "DSSE-PAEv1"
    assert manifest_canon == "RFC8785-v1"


def test_canonicalization_for_v04() -> None:
    """canonicalization_for('v0.4') returns the correct tuple."""
    result = canonicalization_for("v0.4")
    assert result == ("DSSE-PAEv1", "RFC8785-v1")


def test_canonicalization_for_unknown_raises() -> None:
    """canonicalization_for raises ValueError for unknown versions."""
    with pytest.raises(ValueError, match="Unknown dsse_envelope_version"):
        canonicalization_for("v99")
    with pytest.raises(ValueError, match="Unknown dsse_envelope_version"):
        canonicalization_for("")
    with pytest.raises(ValueError, match="Unknown dsse_envelope_version"):
        canonicalization_for("v0.4-rc1")


# ===========================================================================
# 5. payload_type_nfc — NFC normalization golden vector
#
# Vector: NFD "application/tést" (e + combining acute accent, 2 code
#         points for the 'é' position) → NFC "application/tést" (precomposed
#         U+00E9, 1 code point for 'é').
#
# These two strings are Unicode-canonically equivalent but differ at the
# byte level: NFD encodes the 'é' as 0x65 0xcc 0x81 (3 bytes) while NFC
# encodes it as 0xc3 0xa9 (2 bytes).
#
# Source: Unicode Standard §3.7 (Decomposition) + §3.11 (NFC/NFD).
# ===========================================================================

# NFD form: 'e' (U+0065) + combining acute accent (U+0301)
_NFC_INPUT_NFD = "application/tést"  # 18 code points (the 'é' is split)
# NFC form: precomposed 'é' (U+00E9)
_NFC_EXPECTED_NFC = "application/tést"  # 16 code points


def test_payload_type_nfc_normalizes_nfd_to_nfc() -> None:
    """payload_type_nfc converts NFD to NFC form."""
    result = payload_type_nfc(_NFC_INPUT_NFD)
    assert result == _NFC_EXPECTED_NFC, (
        f"NFC normalization failed:\n  got:      {result!r}\n  expected: {_NFC_EXPECTED_NFC!r}"
    )


def test_payload_type_nfc_idempotent() -> None:
    """Applying payload_type_nfc twice is the same as applying it once."""
    once = payload_type_nfc(_NFC_INPUT_NFD)
    twice = payload_type_nfc(once)
    assert once == twice


def test_payload_type_nfc_nfd_bytes_differ_from_nfc() -> None:
    """NFD and NFC forms have different byte representations (proves the test is non-trivial)."""
    nfd_bytes = _NFC_INPUT_NFD.encode("utf-8")
    nfc_bytes = _NFC_EXPECTED_NFC.encode("utf-8")
    assert nfd_bytes != nfc_bytes, "Test is degenerate: NFD and NFC bytes must differ"
    # NFD encodes é as e (0x65) + combining acute (0xcc 0x81) = 3 bytes
    # NFC encodes é as precomposed (0xc3 0xa9) = 2 bytes
    assert b"\xc3\xa9" in nfc_bytes
    assert b"\xcc\x81" in nfd_bytes


def test_payload_type_nfc_ascii_passthrough() -> None:
    """ASCII-only payloadType is unchanged by NFC normalization."""
    ascii_uri = "https://vkernel.dev/types/bundle.v1"
    assert payload_type_nfc(ascii_uri) == ascii_uri


# ===========================================================================
# 6. Import-cleanliness probe — production modules must NOT have imported
#    cryptography, jcs, or rfc8785.
#
# This test confirms that importing audit_bundle.dsse.pae and
# audit_bundle.dsse.version_map does NOT pull in any of the forbidden
# heavy-dep modules.  (Cryptography IS imported in this test file itself
# as an independent cross-check, but that import happens AFTER this probe.)
# ===========================================================================


def test_production_modules_did_not_import_forbidden_deps() -> None:
    """audit_bundle.dsse.pae and version_map must not transitively import cryptography, jcs, or rfc8785.

    NOTE: This test does NOT assert that cryptography is absent from
    sys.modules globally (it is imported in test_kid_from_raw32_cross_checked
    as the independence anchor for the kid vector).  It asserts that the
    production module objects themselves did not introduce those imports.
    """
    # Check that neither pae.py nor version_map.py carries the forbidden attrs.
    forbidden = {"cryptography", "jcs", "rfc8785"}
    for mod in (_pae_mod, _vm_mod):
        for name in forbidden:
            assert not hasattr(mod, name), (
                f"Production module {mod.__name__} has attribute {name!r} — "
                "forbidden dep leaked into production module namespace"
            )

    # The production module's __dict__ must not contain the forbidden module objects.
    for mod in (_pae_mod, _vm_mod):
        for name, val in mod.__dict__.items():
            if isinstance(val, types.ModuleType):
                assert val.__name__.split(".")[0] not in forbidden, (
                    f"Production module {mod.__name__} imported {val.__name__!r} "
                    "(or a submodule of a forbidden dep) at the top level"
                )
