"""_build_bundle.py — build a deterministic content_provenance_minimal audit bundle.

SCOPE BOUNDARY — READ BEFORE PROCEEDING:
This proves WHAT a system produced and that the content has NOT been altered since
it was signed by its stated producer.  It is NOT truth-detection and NOT a
disinformation classifier.  A factually FALSE but unaltered, correctly-signed piece
of content PASSES this check — that is by design and out of scope.

Demonstrates content-provenance verification (C2PA-style problem) for AI-era
information integrity.  A synthetic news-style text artifact is produced by a
synthetic AI system and signed with a producer HMAC key.  The bundle binds:
  - the published content bytes (committed as artifact/content.txt)
  - the producer-signed provenance manifest (committed as artifact/provenance.json)
  - the verification payload (committed as payload/provenance_result.json)

...such that a verifier can independently re-hash the published content bytes and
re-check they match the producer-signed manifest hash, and assert the provenance
chain (producer id + declared generation inputs) is intact and unaltered.  Any
post-signing alteration fails closed.

Honest claim:
  A published content artifact carries a producer-signed manifest binding it to
  its producer identity and generation inputs; the verifier re-confirms the
  artifact's bytes match the signed hash and the provenance chain is intact.
  Any post-signing alteration fails closed.  Synthetic producer key; local-only demo.

Signing primitive: HMAC-SHA256 over the content bytes (stdlib hmac + hashlib).
Mirrors the camera-authenticity pilot signing approach — stdlib only, no 3rd-party deps.

Usage (from v-kernel-audit-bundle root):
    python examples/content_provenance_minimal/_build_bundle.py --out-dir /tmp/content_prov_bundle

Outputs:
  <out-dir>/artifact/content.txt
  <out-dir>/artifact/provenance.json
  <out-dir>/payload/provenance_result.json
  <out-dir>/manifest.json

Exit codes:
  0  success
  1  assertion failure
"""

from __future__ import annotations

import argparse
import hashlib
import hmac
import json
import sys
from pathlib import Path

# §C5 auditor-independence: locate pkg root relative to this file.
# Layout: examples/content_provenance_minimal/_build_bundle.py
#         → parents[2] = pkg root
_PKG_ROOT = Path(__file__).resolve().parents[2]
if str(_PKG_ROOT) not in sys.path:
    sys.path.insert(0, str(_PKG_ROOT))

from audit_bundle.emitter import BundleContent, write_bundle
from audit_bundle.fragments.fragment_id import (
    OpaqueFragment,
    fragment_to_canonical_dict,
)

_SCHEMA_VERSION = "vcp-v1.1-canary4"
_BUNDLE_ID = "content-provenance-minimal-rc"
_CREATED_AT = "2026-05-29T00:00:00Z"
_TYPED_CHECKS = [
    "file_integrity_many_small",
    "content_provenance_re_derivation",
]

# Synthetic producer key — deterministic bytes, local-only demo, NOT a real secret.
# Using a fixed key ensures the bundle is fully reproducible across builds.
_SYNTHETIC_PRODUCER_KEY = b"SYNTHETIC_PRODUCER_KEY_LOCAL_DEMO_ONLY_NOT_A_SECRET"


# ---------------------------------------------------------------------------
# Synthetic fixture generation (deterministic, stdlib-only)
# ---------------------------------------------------------------------------


def _make_synthetic_content() -> bytes:
    """Construct a synthetic news-style text artifact (deterministic).

    Simulates a news article generated by an AI writing assistant.
    The text is entirely static (no randomness) to keep the bundle
    fully deterministic across builds.
    """
    article = (
        "SYNTHETIC NEWS ARTICLE — AI-GENERATED DEMO CONTENT\n"
        "====================================================\n"
        "\n"
        "Scientists Announce Breakthrough in Renewable Energy Storage\n"
        "\n"
        "Researchers at the Synthetic Institute of Technology announced today\n"
        "a new battery technology capable of storing 10x more energy per\n"
        "kilogram than current lithium-ion solutions.  The announcement was\n"
        "made at the annual Clean Energy Summit.\n"
        "\n"
        "NOTE: This is synthetic demo content generated for audit-bundle\n"
        "      pilot purposes.  The claim above is fabricated.  This pilot\n"
        "      demonstrates content PROVENANCE (who signed this and when)\n"
        "      NOT factual accuracy or truth-verification.\n"
        "\n"
        "Producer: NexiWriter/1.0 (synthetic)\n"
        "Generated: 2026-05-29T00:00:00Z\n"
        "Prompt-hash: sha256:a3f2...  (committed in provenance manifest)\n"
    )
    return article.encode("utf-8")


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _producer_hmac(key: bytes, data: bytes) -> str:
    """HMAC-SHA256 over data using key.  Returns hex string.

    Signing primitive mirrored from the camera-authenticity pilot approach:
    stdlib hmac + hashlib, no 3rd-party deps.  This is NOT a real production
    signing scheme — it demonstrates the structural binding pattern.
    """
    return hmac.new(key, data, hashlib.sha256).hexdigest()


def _make_provenance_manifest(
    content_sha: str,
    producer_id: str,
    generation_inputs: dict,
    producer_hmac_hex: str,
) -> dict:
    """Construct the producer-signed provenance manifest.

    Fields:
      producer_id       — identity of the AI system that produced the content
      content_sha       — SHA-256 of the published content bytes
      generation_inputs — declared inputs used during generation (prompt hash, model id)
      producer_hmac     — HMAC-SHA256(key, content_bytes) proving producer signed these bytes
      created_at        — timestamp of signing
      note              — honest scope disclaimer

    SCOPE BOUNDARY NOTE: this manifest proves the content was produced and signed
    by the declared producer with unaltered bytes.  It does NOT prove the content
    is factually true.  A false article signed by its AI producer PASSES this check.
    """
    return {
        "schema": "content-provenance-v1",
        "producer_id": producer_id,
        "content_sha": f"sha256:{content_sha}",
        "generation_inputs": generation_inputs,
        "producer_hmac": f"hmac-sha256:{producer_hmac_hex}",
        "created_at": _CREATED_AT,
        "note": (
            "Synthetic provenance manifest — local demo only.  "
            "HMAC key is a hardcoded synthetic key, NOT a real production secret.  "
            "Proves content bytes are unaltered since producer signing; "
            "does NOT prove content is factually accurate."
        ),
    }


# ---------------------------------------------------------------------------
# Bundle builder
# ---------------------------------------------------------------------------


def build(out_dir: Path) -> None:
    producer_id = "NexiWriter/1.0-synthetic"
    generation_inputs = {
        "prompt_sha": "sha256:a3f2b8c4d1e9f056789012345678901234567890abcdef0123456789abcdef01",
        "model_id": "nexi-writer-v1-synthetic",
        "temperature": 0.7,
        "note": "Synthetic generation inputs — no real model was invoked",
    }

    # --- Generate synthetic content ---
    content_bytes = _make_synthetic_content()
    content_sha = _sha256(content_bytes)

    # --- Sign: HMAC-SHA256(synthetic_key, content_bytes) ---
    producer_hmac_hex = _producer_hmac(_SYNTHETIC_PRODUCER_KEY, content_bytes)

    # --- Build provenance manifest ---
    provenance_dict = _make_provenance_manifest(
        content_sha=content_sha,
        producer_id=producer_id,
        generation_inputs=generation_inputs,
        producer_hmac_hex=producer_hmac_hex,
    )
    provenance_bytes = json.dumps(provenance_dict, indent=2, sort_keys=True).encode("utf-8")
    provenance_sha = _sha256(provenance_bytes)

    # --- Build verification payload ---
    provenance_result = {
        "content_sha": content_sha,
        "provenance_sha": provenance_sha,
        "producer_id": producer_id,
        "generation_inputs": generation_inputs,
        "producer_hmac": f"hmac-sha256:{producer_hmac_hex}",
        "provenance_status": "CONTENT_PROVENANCE_VERIFIED",
    }
    provenance_result_bytes = json.dumps(
        provenance_result, indent=2, sort_keys=True
    ).encode("utf-8")

    # --- Fragment anchor: OpaqueFragment for the content artifact ---
    content_fragment = OpaqueFragment(
        source_cid=f"sha256:{content_sha}",
        kind_tag="content_artifact",
        locator={
            "path": "artifact/content.txt",
            "format": "utf8_text",
            "producer_id": producer_id,
        },
    )
    fragment_anchors = {
        "content-artifact-001": fragment_to_canonical_dict(content_fragment),
    }

    # --- Emit via the reference-emitter SDK (scaffold + digests + manifest). ---
    content = BundleContent(
        bundle_id=_BUNDLE_ID,
        created_at=_CREATED_AT,
        schema_version=_SCHEMA_VERSION,
        files={
            "artifact/content.txt": content_bytes,
            "artifact/provenance.json": provenance_bytes,
            "payload/provenance_result.json": provenance_result_bytes,
        },
        payload={"provenance_result": "payload/provenance_result.json"},
        typed_checks=_TYPED_CHECKS,
        extra_manifest_fields={
            "fragment_anchors": fragment_anchors,
            "snapshots": {},
            "snapshot_policy": None,
        },
    )
    write_bundle(out_dir, content)
    manifest_path = out_dir / "manifest.json"

    print(f"Bundle written to {out_dir}")
    print(f"  content artifact : artifact/content.txt ({len(content_bytes)} bytes)")
    print(f"  content sha256   : {content_sha}")
    print(f"  producer id      : {producer_id}")
    print(f"  producer hmac    : hmac-sha256:{producer_hmac_hex[:16]}...")
    print(f"  provenance       : artifact/provenance.json")
    print(f"  payload          : payload/provenance_result.json")
    print(f"  manifest         : {manifest_path}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build a deterministic content_provenance_minimal audit bundle"
    )
    parser.add_argument(
        "--out-dir",
        required=True,
        type=Path,
        help="Destination directory (created if absent)",
    )
    args = parser.parse_args()
    try:
        build(args.out_dir.resolve())
    except AssertionError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
